### ISSUE TITLE
Fix: wrong display of UserName tag

### ISSUE THREAD

**Issue by ganzenman** [sidestep-labs/AzureKeyVaultExplorer#101]
Hi,
i noticed this behavior.
![Knipsel](https://github.com/user-attachments/assets/b4ebffa6-3b47-407c-90b5-bc98c6ece3a1)
The tag, we created ourselves, UserName has the value:    s_Automic_ldapsynch
But the readout in the details pane is     sAutomic_ldapsynch
When you would search for sAutomic_ldapsynch nothing would be returned

this is but a cosmetic issue

keep up the good work!

**Comment by cricketthomas** [comment]
This is really interesting. I'll investigate.

**Comment by cricketthomas** [comment]
This will be available in the microsoft store later on monday.
