### ISSUE TITLE
The Search bar could filter by ContentType field, not only by name and tags

### ISSUE THREAD

**Issue by eriksrocha** [sidestep-labs/AzureKeyVaultExplorer#98]
The Search bar could filter by ContentType field, not only by name and tags

![image](https://github.com/user-attachments/assets/67bde6b5-c4ed-4715-9a1b-9e57822ab246)

**Comment by cricketthomas** [comment]
@eriksrocha This has been completed, should be in the microsoft store monday. 
Also, if you could consider doing any of the following if you have time:

1. If you have a moment and could vote in this poll or share it with anyone: https://github.com/sidestep-labs/AzureKeyVaultExplorer/discussions/97
2. Leave a review, on the application on the microsoft store, a genuine, unbiased review.
